### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/ets-dgiwg-core#2]
This code has a dependency on teamengine-spi version 5.0.  The build fails when building this against a later version of teamengine.

**Comment by dstenger** [comment]
Thank you for reporting.

@keshav-nangare Can you please do further investigations?

**Comment by ajanett** [comment]
I am building a configuration with TEAM Engine 5.2.  The package ets-wfs20-nsg has a dependency on ets-dgiwg-core version 0.4 (and it does not build with version 0.3) The ets-dgiwg-core version 0.4 then fails to build due to a dependency on teamengine-spi version 5.0.  Changing the pom to reference teamengine-spi version 5.2 fixes the problem, but I am not sure if it should have been a problem in the first place. Hence this issue report on a dependency.

**Comment by dstenger** [comment]
I tried to build (using ```mvn clean install```) this project with TEAM Engine 5.0 and 5.2 and it worked with both versions.

5.2 is available via Central Maven Repository and 5.0 is not available remotely (in this case, you have to build it locally first). Maybe this led to the failure of your build?

**Comment by ajanett** [comment]
My goal is to use TEAM Engine 5.2 and I don't believe I should have to build and install TEAM Engine 5.0 as well just to satisfy this dependency, hence this issue report. Ultimately, the question is, can the change be made to ets-dgiwg-core so that it is non-version specific with respect to TEAM Engine dependencies?  Is there some critical reason that it requires TEAM Engine 5.0?  I am simply looking for a clean build of the system based on a checkout of this tool at revision 0.4 with TEAM Engine 5.2 and ets-wfs20-nsg.

**Comment by dstenger** [comment]
Short technical explanation why dependency to TEAM Engine 5.0 is existing:
TEAM Engine jar also provides interfaces which must be implemented by individual test suites (e.g. TestSuiteController). Thus, a dependency to TEAM Engine is required. As last release of ets-dgiwg-core was created quite a while ago, TEAM Engine version has not been updated yet.

However, I totally agree that this dependency should be avoided. My proposal is to extract those interfaces to a new project (e.g. teamengine-ets-api or teamengine-api) which can be used by TEAM Engine and test suites then. By this, we remove the dependency of all test suites to TEAM Engine.
I created an issue for that: https://github.com/opengeospatial/teamengine/issues/335

**Comment by ajanett** [comment]
Thank you for the explanation.

**Comment by dstenger** [comment]
I propose to update dependency to TEAM Engine 5.2 and then close this issue.

**Comment by keshavnangare** [comment]
Fixed with this commit: 3c9d05f7f5ac9772255c8bfa97188027a52158ac
